import { Schema, model } from "mongoose";

/**
 * A festival, the screenings it programmes, and the films in each.
 *
 * IFFA runs ONE festival a year. `year` is stored rather than derived, and
 * carries a unique index, so that rule is enforced by the database instead of
 * being a convention staff have to remember — a second festival in a year the
 * calendar already holds cannot be written at all. It is always recomputed
 * server-side from `startDate`, never accepted from the client, so the year and
 * the dates can never drift apart.
 *
 * This replaced a two-festivals-a-month model. The public site used to render
 * month -> festival -> screening; it now renders one festival and files the
 * rest as an archive.
 *
 * Screenings are embedded rather than a collection of their own, and films are
 * embedded in screenings: a screening belongs to exactly one festival, a film
 * to exactly one screening, neither is ever queried on its own, and both are
 * always read with their parent. Embedding keeps a festival one atomic
 * document, keeps programme order without a sort key war, and means a delete
 * takes the whole tree with it.
 *
 * MONGOOSE TRAP (see AGENTS.md): a field declared only on the TypeScript
 * interface is silently dropped on save. Every field below appears in BOTH the
 * interface and the Schema object. When adding one, do the same and verify
 * with a real query.
 */

export const SEAT_STATUSES = ["available", "limited", "sold-out"] as const;
export type SeatStatus = (typeof SEAT_STATUSES)[number];

/**
 * One film in a screening.
 *
 * Carries nothing about when or where it plays. That used to live here,
 * because a screening WAS a film; it now lives on the screening, which is the
 * thing a time and a venue actually describe.
 */
export interface IFilm {
  title: string;
  /** CloudFront URL. Empty means "no artwork yet" — the site draws a typographic poster. */
  posterUrl?: string;
  /**
   * S3 object key backing posterUrl, set only for posters uploaded through the
   * CMS. Empty for an externally-hosted URL — which is what makes it safe as a
   * delete target: we only ever delete objects this app put there itself.
   */
  posterKey?: string;
  /** Country of origin. Shown on every card; never a filter. */
  country: string;
  /** Year of production, not of the screening. */
  year: number;
  genre?: string;
  runtimeMinutes?: number;
  synopsis?: string;
  /** Raw YouTube URL. Empty means no trailer is available. */
  trailerUrl?: string;
}

/**
 * One session on the programme: a named block of films at a time and place.
 *
 * A screening used to be a single film. That collapsed as soon as a session
 * programmed more than one title — a shorts block of six had to be entered as
 * six screenings sharing a time and a venue, with nothing tying them together
 * and nowhere to put the block's own name or blurb.
 *
 * `startDate` and `endDate` are usually the same day. A strand that repeats
 * across several days sets a real range, which is why the public programme
 * cannot group by night any more.
 */
export interface IScreening {
  title: string;
  /** A short blurb for the session as a whole. */
  description?: string;
  /** ISO date the session opens, e.g. "2026-08-07". */
  startDate: string;
  /** ISO date it closes. Equal to startDate for a single sitting. */
  endDate: string;
  /** Display-ready local start time, e.g. "7:30 PM". */
  time: string;
  venue?: string;
  seatStatus: SeatStatus;
  /** In programme order, as entered in the CMS. */
  films: IFilm[];
}

export interface IFestival {
  /** URL segment on the public site: /festivals/<slug>. Unique. */
  slug: string;
  /**
   * The festival year. Unique across the collection: one festival a year.
   *
   * Recomputed from `startDate` on every write. A festival that straddles New
   * Year belongs to the year it opens in, which is also how it is billed.
   */
  year: number;
  /**
   * Folder-level uniqueness token for this festival's S3 assets, generated by
   * the CMS when the "new festival" form is opened. Festival names are neither
   * unique nor stable, so two "Crossings" would otherwise overwrite each
   * other's artwork silently — S3 PUT overwrites without error.
   */
  assetRef: string;
  /**
   * Recomputed server-side from assetRef + name on every write. Never accepted
   * from the client: this string is the path a prefix-delete walks.
   */
  assetPrefix?: string;
  name: string;
  tagline?: string;
  description?: string;
  heroImageUrl?: string;
  heroImageKey?: string;
  city?: string;
  /** ISO dates. The public site derives every label and range from these. */
  startDate: string;
  endDate: string;
  /** Lets staff draft a festival before announcing it. Public API returns published only. */
  isPublished?: boolean;
  screenings: IScreening[];
}

const filmSchema = new Schema<IFilm>(
  {
    title: { type: String, required: true, trim: true, maxLength: 300 },
    posterUrl: { type: String, default: "", trim: true },
    posterKey: { type: String, default: "", trim: true },
    country: { type: String, default: "", trim: true, maxLength: 120 },
    year: { type: Number, default: 0 },
    genre: { type: String, default: "", trim: true, maxLength: 120 },
    runtimeMinutes: { type: Number, default: 0 },
    synopsis: { type: String, default: "", trim: true, maxLength: 4000 },
    trailerUrl: { type: String, default: "", trim: true },
  },
  { _id: true },
);

const screeningSchema = new Schema<IScreening>(
  {
    title: { type: String, required: true, trim: true, maxLength: 300 },
    description: { type: String, default: "", trim: true, maxLength: 4000 },
    // MONGOOSE TRAP (see AGENTS.md): startDate/endDate/films must exist here
    // as well as on the interface, or they are silently dropped on save.
    startDate: { type: String, required: true, trim: true },
    endDate: { type: String, required: true, trim: true },
    time: { type: String, default: "", trim: true, maxLength: 40 },
    venue: { type: String, default: "", trim: true, maxLength: 200 },
    seatStatus: { type: String, enum: SEAT_STATUSES, default: "available" },
    films: { type: [filmSchema], default: [] },
  },
  // Subdocument _ids are kept: the CMS edits screenings by id. The public site
  // does NOT use them as links — it mints its own ids from the title, because
  // saving a festival rewrites the embedded array and reissues these.
  { _id: true },
);

const festivalSchema = new Schema<IFestival>(
  {
    slug: {
      type: String,
      required: true,
      trim: true,
      lowercase: true,
      unique: true,
      maxLength: 120,
    },
    // Unique, and the reason a second festival in one year is impossible.
    // MONGOOSE TRAP: this must exist here as well as on the interface.
    year: { type: Number, required: true, unique: true },
    assetRef: { type: String, required: true, trim: true, maxLength: 16 },
    assetPrefix: { type: String, default: "", trim: true },
    name: { type: String, required: true, trim: true, maxLength: 200 },
    tagline: { type: String, default: "", trim: true, maxLength: 300 },
    description: { type: String, default: "", trim: true, maxLength: 4000 },
    heroImageUrl: { type: String, default: "", trim: true },
    heroImageKey: { type: String, default: "", trim: true },
    city: { type: String, default: "", trim: true, maxLength: 120 },
    startDate: { type: String, required: true, trim: true },
    endDate: { type: String, required: true, trim: true },
    isPublished: { type: Boolean, default: false },
    screenings: { type: [screeningSchema], default: [] },
  },
  { timestamps: true },
);

// The public API returns the most recent festival first, so the archive on the
// site is already in the order it renders.
festivalSchema.index({ startDate: -1 });

const Festival = model("Festival", festivalSchema);
export default Festival;
